services:



  person_detection_api:
    image: public.ecr.aws/g7a8t7v6/inference-container:...
    ports:
      - "3000:3000"
    command:
      [
        "--api-key", "EI_API_KEY",
        "--run-http-server", "3000",
        "--impulse-id", "2",
        "--force-variant", "int8"
      ]
    restart: unless-stopped

  n8n:
    image: n8nio/n8n:latest
    restart: unless-stopped
    ports:
      - "8743:5678"
    environment:
      - N8N_HOST=aboglion.top
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://aboglion.top:8743/
      - NODE_ENV=production
      - GENERIC_TIMEZONE=Asia/Jerusalem
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - N8N_SSL_KEY=/home/node/.n8n/ssl/privkey.pem
      - N8N_SSL_CERT=/home/node/.n8n/ssl/fullchain.pem
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
    volumes:
      - ./n8n:/home/node/.n8n



