services:


  trader:
    build: ./TRADER
    ports:
      - "7070:7070"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./TRADER:/app

  n8n:
    image: n8nio/n8n:latest
    restart: unless-stopped
    ports:
      - "8743:5678"
    environment:
      - N8N_HOST=aboglion.top
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://aboglion.top:8743/
      - NODE_ENV=production
      - GENERIC_TIMEZONE=Asia/Jerusalem
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - N8N_SSL_KEY=/home/node/.n8n/ssl/privkey.pem
      - N8N_SSL_CERT=/home/node/.n8n/ssl/fullchain.pem
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - NODE_FUNCTION_ALLOW_EXTERNAL=*


    volumes:
      - ./n8n:/home/node/.n8n


  nginx:
    image: nginx:latest
    ports:
      - "8743:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - n8n
