version: "3.8"

networks:
  app_net:
    driver: bridge

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    environment:
      - N8N_HOST=aboglion.top
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - N8N_EDITOR_BASE_URL=https://aboglion.top:8744/
      - WEBHOOK_TUNNEL_URL=https://aboglion.top:8744/
      - NODE_ENV=production
      - GENERIC_TIMEZONE=Asia/Jerusalem
      - NODE_FUNCTION_ALLOW_EXTERNAL=*
      - N8N_USER_FOLDER=/home/node/.n8n
      - DB_TYPE=sqlite
      - DB_SQLITE_POOL_SIZE=5  # Pool size לשיפור ביצועים
      - N8N_RUNNERS_ENABLED=true # Enables task runners for better parallelism
      - N8N_BASIC_AUTH_ACTIVE=false
      - N8N_BASIC_AUTH_USER=
      - N8N_BASIC_AUTH_PASSWORD=
    volumes:
      - ../data_backup/n8n_data:/home/node/.n8n
    networks:
      - app_net
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M
        reservations:
          cpus: '0.5'
          memory: 512M

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "8744:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy/ssl:/etc/caddy/ssl:ro
    depends_on:
      - n8n
    networks:
      - app_net
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M

  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    restart: unless-stopped
    ports:
      - "8181:8080"
    volumes:
      - ./searxng/settings.yml:/etc/searxng/settings.yml:ro
    environment:
      - UWSGI_WORKERS=4
      - UWSGI_THREADS=4
    networks:
      - app_net
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
