version: "3.8"

networks:
  app_net:
    driver: bridge

services:
  trader:
    build: ./TRADER
    container_name: trader
    ports:
      - "7070:7070"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ../data_backup/TRADER/LOGS:/trader_app/LOGS

    networks:
      - app_net

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    ports:
      - "8743:5678"
    environment:
      - N8N_HOST=aboglion.top
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - N8N_EDITOR_BASE_URL=https://aboglion.top:8744/
      - WEBHOOK_TUNNEL_URL=https://aboglion.top:8744/
      - NODE_ENV=production
      - GENERIC_TIMEZONE=Asia/Jerusalem
      - NODE_FUNCTION_ALLOW_EXTERNAL=*
      - N8N_USER_FOLDER=/home/node/.n8n

    volumes:
      - ../data_backup/n8n_data:/home/node/.n8n:rw
    networks:
      - app_net

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8744:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./TRADER/static:/TRADER/static:ro
    depends_on:
      - n8n
      - trader
    networks:
      - app_net
