version: "3"
services:
  person_detection_api:
    build: ./Person_Detection_API
    ports:
      - "3000:3000"
    volumes:
      - .:/Person_Detection_API
    environment:
      - ENV=development
      - FLASK_ENV=development
      - SERVER_TYPE=flask  # Use Flask development server
    restart: unless-stopped

  n8n:
    image: n8nio/n8n:latest
    ports:
      - "8743:5678"
    environment:
      - N8N_HOST=n8n
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=development
      - WEBHOOK_URL=https://localhost:8743/
      - GENERIC_TIMEZONE=Asia/Jerusalem
      - N8N_LOG_LEVEL=debug  # More verbose logging for development
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - N8N_SSL_KEY=/home/node/.n8n/ssl/privkey.pem
      - N8N_SSL_CERT=/home/node/.n8n/ssl/fullchain.pem
    volumes:
      - ./n8n/ssl:/home/node/.n8n/ssl
      - ./n8n/data:/home/node/.n8n
    restart: unless-stopped