version: "3.8"

networks:
  app_net:
    driver: bridge

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    environment:
      - N8N_HOST=aboglion.top
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - N8N_EDITOR_BASE_URL=https://aboglion.top:8744/
      - WEBHOOK_TUNNEL_URL=https://aboglion.top:8744/
      - NODE_ENV=production
      - GENERIC_TIMEZONE=Asia/Jerusalem
      - NODE_FUNCTION_ALLOW_EXTERNAL=*
      - N8N_USER_FOLDER=/home/node/.n8n
    volumes:
      - ../data_backup/n8n_data:/home/node/.n8n
    networks:
      - app_net

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "8744:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy/ssl:/etc/caddy/ssl:ro
    depends_on:
      - n8n
    networks:
      - app_net
