services:


  trader:
    build: ./TRADER
    ports:
      - "7070:7070"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ../data_backup/TRADER/LOGS:/app/LOGS

  n8n:
    image: n8nio/n8n:latest
    restart: unless-stopped
    ports:
      - "8743:5678"
    environment:
      - N8N_HOST=aboglion.top
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - GENERIC_TIMEZONE=Asia/Jerusalem
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - NODE_FUNCTION_ALLOW_EXTERNAL=*
      # - WEBHOOK_URL=https://aboglion.top:8743/
    volumes:
      - ../data_backup/n8n_data/:/home/node/.n8n


  nginx:
    image: nginx:latest
    ports:
      - "8744:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - n8n


