server:
  bind_address: "0.0.0.0"
  port: 8080
  base_url: ""
  secret_key: "younis.aboglion"

  access_control:
    allow:
      - 0.0.0.0/0

default_doi_resolver:
  - crossref

doi_resolver:
  - crossref
  - datacite
  - opendoi
  - aister
  - medra

search:
  formats:
    - html
    - json

engines:
  - name: google
    shortcut: g
    engine: google
    base_url: https://www.google.com/search
    encoding: utf-8
    params:
      q: '{{ query }}'

  - name: bing
    shortcut: b
    engine: bing
    base_url: https://www.bing.com/search
    encoding: utf-8
    params:
      q: '{{ query }}'

  - name: duckduckgo
    shortcut: d
    engine: duckduckgo
    base_url: https://duckduckgo.com/html/
    encoding: utf-8
    params:
      q: '{{ query }}'

logging:
  level: INFO
  file: /var/log/searxng/searxng.log

cache:
  enabled: false
  expiration: 3600

pagination:
  results_per_page: 10
